### ISSUE TITLE
iLO4 - ParseError: no element found

### ISSUE THREAD

**Issue by nickthebeer** [infinityworksltd/hpilo-exporter#16]
I've been running a few iLO containers for a while now and I keep seeing the following error occur. The frequency is sporadic, some containers don't error for months, others are many times a day and the ones erroring frequently are not always the same ones. The error out of the logs is as follows:

`hpilo-exporter-4_1       | 172.18.0.34 - - [18/Aug/2021 00:42:19] "GET /metrics?ilo_port=443&ilo_user=monitoring HTTP/1.1" 200 -
hpilo-exporter-4_1       | 172.18.0.34 - - [18/Aug/2021 00:46:19] "GET /metrics?ilo_port=443&ilo_user=monitoring HTTP/1.1" 200 -
hpilo-exporter-4_1       | 172.18.0.34 - - [18/Aug/2021 00:50:20] "GET /metrics?ilo_port=443&ilo_user=monitoring HTTP/1.1" 200 -
hpilo-exporter-4_1       | 172.18.0.34 - - [18/Aug/2021 00:54:20] "GET /metrics?ilo_port=443&ilo_user=monitoring HTTP/1.1" 200 -
hpilo-exporter-4_1       | 172.18.0.34 - - [18/Aug/2021 00:58:20] "GET /metrics?ilo_port=443&ilo_user=monitoring HTTP/1.1" 200 -
hpilo-exporter-4_1       | 172.18.0.34 - - [18/Aug/2021 01:02:20] "GET /metrics?ilo_port=443&ilo_user=monitoring HTTP/1.1" 200 -
hpilo-exporter-4_1       | 172.18.0.34 - - [18/Aug/2021 01:06:21] "GET /metrics?ilo_port=443&ilo_user=monitoring HTTP/1.1" 200 -
hpilo-exporter-4_1       | 172.18.0.34 - - [18/Aug/2021 01:10:21] "GET /metrics?ilo_port=443&ilo_user=monitoring HTTP/1.1" 200 -
hpilo-exporter-4_1       | Traceback (most recent call last):
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
hpilo-exporter-4_1       |     self.finish_request(request, client_address)
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
hpilo-exporter-4_1       |     self.RequestHandlerClass(request, client_address, self)
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
hpilo-exporter-4_1       |     self.handle()
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
hpilo-exporter-4_1       |     self.handle_one_request()
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
hpilo-exporter-4_1       |     method()
hpilo-exporter-4_1       |   File "/usr/src/hpilo_exporter/src/hpilo_exporter/exporter.py", line 159, in do_GET
hpilo-exporter-4_1       |     metrics = iloGetMetrics(ilo_host, ilo_port, ilo_user, ilo_password)
hpilo-exporter-4_1       |   File "/usr/src/hpilo_exporter/src/hpilo_exporter/exporter.py", line 69, in iloGetMetrics
hpilo-exporter-4_1       |     health_at_glance = ilo.get_embedded_health()['health_at_a_glance']
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/site-packages/hpilo.py", line 961, in get_embedded_health
hpilo-exporter-4_1       |     process=process)
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/site-packages/hpilo.py", line 698, in _info_tag
hpilo-exporter-4_1       |     header, message = self._request(root)
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/site-packages/hpilo.py", line 250, in _request
hpilo-exporter-4_1       |     message = self._parse_message(data)
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/site-packages/hpilo.py", line 556, in _parse_message
hpilo-exporter-4_1       |     message = etree.fromstring(data)
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1312, in XML
hpilo-exporter-4_1       |     return parser.close()
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1665, in close
hpilo-exporter-4_1       |     self._raiseerror(v)
hpilo-exporter-4_1       |   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
hpilo-exporter-4_1       |     raise err
hpilo-exporter-4_1       | ParseError: no element found: line 409, column 46
`

**Comment by nickthebeer** [comment]
I found the issue, the issues arises when iLO accepts the login but does not provide a valid response, I believe it is due to too many API calls but haven't been able to confirm this yet.
